blank_issues_enabled: false
contact_links:
  - name: Asaas support
    url: https://support.asaas.com/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the Asaas Ruby library.

      If you're having general trouble with your Asaas integration, please reach out to support.
